[package]
name = "ddn-observability-testing"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1"
async-trait = "0.1"
opentelemetry-proto = "0.5"
tokio = { version = "1", features = ["full"] }
